# Generated by Django 2.2.16 on 2020-09-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.SmallIntegerField()),
                ('contact_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=60)),
                ('type_of_pet', models.CharField(max_length=60)),
                ('species', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('intro', models.TextField()),
                ('pet_owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='petapi.User')),
            ],
        ),
    ]
